/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MockV3AggregatorInterface extends Interface {
    getFunction(nameOrSignature: "latestRoundData" | "updatePrice"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'latestRoundData', values?: undefined): string;
encodeFunctionData(functionFragment: 'updatePrice', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'latestRoundData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePrice', data: BytesLike): Result;
  }

  

  export interface MockV3Aggregator extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockV3Aggregator;
    waitForDeployment(): Promise<this>;

    interface: MockV3AggregatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    latestRoundData: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >
    

    
    updatePrice: TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'latestRoundData'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint] & {roundId: bigint, answer: bigint, startedAt: bigint, updatedAt: bigint, answeredInRound: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'updatePrice'): TypedContractMethod<
      [newPrice: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }