/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MockV3Aggregator, MockV3AggregatorInterface } from "../../test/MockV3Aggregator.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "initialPrice",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newPrice",
        "type": "int256"
      }
    ],
    "name": "updatePrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060405161026f38038061026f8339818101604052810190602e9190606b565b805f81905550506091565b5f5ffd5b5f819050919050565b604d81603d565b81146056575f5ffd5b50565b5f815190506065816046565b92915050565b5f60208284031215607d57607c6039565b5b5f6088848285016059565b91505092915050565b6101d18061009e5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063d4c19bda14610038578063feaf968c14610054575b5f5ffd5b610052600480360381019061004d91906100d4565b610076565b005b61005c61007f565b60405161006d95949392919061014a565b60405180910390f35b805f8190555050565b5f5f5f5f5f60015f5442426001945094509450945094509091929394565b5f5ffd5b5f819050919050565b6100b3816100a1565b81146100bd575f5ffd5b50565b5f813590506100ce816100aa565b92915050565b5f602082840312156100e9576100e861009d565b5b5f6100f6848285016100c0565b91505092915050565b5f69ffffffffffffffffffff82169050919050565b61011d816100ff565b82525050565b61012c816100a1565b82525050565b5f819050919050565b61014481610132565b82525050565b5f60a08201905061015d5f830188610114565b61016a6020830187610123565b610177604083018661013b565b610184606083018561013b565b6101916080830184610114565b969550505050505056fea2646970667358221220d809d7b22fb59cb970fbdf203d2cb8838de66c7a4a6f3543cdfb61bbd9fc93c264736f6c634300081c0033";

  
      type MockV3AggregatorConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockV3AggregatorConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockV3Aggregator__factory extends ContractFactory {
    
      constructor(...args: MockV3AggregatorConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(initialPrice, overrides || {});
    };
    override deploy(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(initialPrice, overrides || {}) as Promise<MockV3Aggregator & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockV3Aggregator__factory {
      return super.connect(runner) as MockV3Aggregator__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockV3AggregatorInterface {
      return new Interface(_abi) as MockV3AggregatorInterface;
    }
    
    override attach(address: string | Addressable): MockV3Aggregator {
      return super.attach(address) as MockV3Aggregator;
    }
  static connect(address: string, runner?: ContractRunner | null): MockV3Aggregator {
      return new Contract(address, _abi, runner) as unknown as MockV3Aggregator;
    }
  }

  
  