/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Counter', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Counter__factory>
getContractFactory(name: 'NexusDAO', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NexusDAO__factory>
getContractFactory(name: 'NexusNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NexusNFT__factory>
getContractFactory(name: 'NexusStaking', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NexusStaking__factory>
getContractFactory(name: 'NexusToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NexusToken__factory>
getContractFactory(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockV3Aggregator__factory>

  getContractAt(name: 'Counter', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Counter>
getContractAt(name: 'NexusDAO', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NexusDAO>
getContractAt(name: 'NexusNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NexusNFT>
getContractAt(name: 'NexusStaking', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NexusStaking>
getContractAt(name: 'NexusToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NexusToken>
getContractAt(name: 'MockV3Aggregator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'Counter', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'NexusDAO', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusDAO>
deployContract(name: 'NexusNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusNFT>
deployContract(name: 'NexusStaking', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusStaking>
deployContract(name: 'NexusToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusToken>
deployContract(name: 'MockV3Aggregator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

  deployContract(name: 'Counter', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Counter>
deployContract(name: 'NexusDAO', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusDAO>
deployContract(name: 'NexusNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusNFT>
deployContract(name: 'NexusStaking', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusStaking>
deployContract(name: 'NexusToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NexusToken>
deployContract(name: 'MockV3Aggregator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockV3Aggregator>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  